### ISSUE TITLE
YAML document causing errors in the output tab (seems to be assuming json?)

### ISSUE THREAD

**Issue by reidca** [awslabs/aws-cfn-lint-visual-studio-code#11]
Settings have been updated...
Settings: {"cfnLint":{"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Is CFN: true
running............. cfn-lint --format,json,--template,c:\source\aws\cloudformation\stacksets\staff-roles.yaml
child process exited with code 4 and signal null
[Error - 09:57:26] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 
Running cfn-lint...
Is CFN: true
running............. cfn-lint --format,json,--template,c:\source\aws\cloudformation\stacksets\staff-roles.yaml
child process exited with code 2 and signal null
Running cfn-lint...
Is CFN: true
running............. cfn-lint --format,json,--template,c:\source\aws\cloudformation\stacksets\staff-roles.yaml
child process exited with code 4 and signal null

**Comment by kddejong** [comment]
just release v0.1.2 should be available shortly.  Can you test it out?

**Comment by z0ph** [comment]
Same issue here: `cfn-lint 0.26.1`

```
Running cfn-lint...
Determined this file is a CloudFormation Template. file:///Users/xxx/Documents/tools/xxx-vpc/template.yaml. Found the string AWSTemplateFormatVersion
running............. cfn-lint --format,json,--,"/Users/xxx/Documents/tools/xxx-vpc/template.yaml"
child process exited with code 0 and signal null
```
