### ISSUE TITLE
How to use with *.template files

### ISSUE THREAD

**Issue by panzupa** [awslabs/aws-cfn-lint-visual-studio-code#19]
How to use this plugin with `*.template` files which are written in YAML ?

**Comment by kddejong** [comment]
The language mode also needs to be `YAML` or `JSON` depending on the format of your .template file.  It ends up being a two step process.  We use the `AWSTemplateFormatVersion: '2010-09-09'` to determine if the yaml or json file is a CloudFormation template.

**Comment by kddejong** [comment]
oh good.  Glad you got this working @panzupa
