### ISSUE TITLE
Failure to detect CloudFormation templates

### ISSUE THREAD

**Issue by acdha** [awslabs/aws-cfn-lint-visual-studio-code#20]
I have `cfn-lint` installed in my path but any time I'm working on a file I have no linter output and the output log shows only this message repeated for every save:

```
File 'file:///[elided]/service.yaml is a CFN? false
```

This happens whether I have it installed using Python 2 or 3, in the path or a separate virtualenv, or with the config cfn-lint path set or not. Is there a better way to get debug output to narrow down the cause?

**Comment by cmmeyer** [comment]
We are using the CloudFormation version string within the template to determine if the file should be linted.  Your template must containt the following string for the linter to pick it up:

AWSTemplateFormatVersion: '2010-09-09'

Does that help?

**Comment by acdha** [comment]
Ah, that was indeed it. Maybe this is just a combination of the error message say more about what it didn't find and perhaps having cfn-lint report that too?

**Comment by kddejong** [comment]
yea this has been trick @acdha because we don't want to lint all yaml or json files that you may open so we use that string to determine if we should/can lint it.  I'm open to suggestions here.  Maybe we could log something that says we didn't lint the file because it was missing the version.

**Comment by acdha** [comment]
I think that would make a lot of sense - you could probably add a couple more keys to look for but the simplest thing would be making it easier for someone like me to see that log message and know what to do to change it.

**Comment by kddejong** [comment]
Released with v0.2.3.
