### ISSUE TITLE
Cannot start cfn-lint in VSCode

### ISSUE THREAD

**Issue by skokovic** [awslabs/aws-cfn-lint-visual-studio-code#21]
Hello there!

I've installed cfn-lint with pip3:
`pip3 install cfn-lint --user`

When I run `cfn-lint --version`, I get:
cfn-lint 0.7.4 
So the linter is working as expected in the terminal.

With vscode-fn-lint 0.2.2 version
But when I load a CloudFormation script into VSCode, I get the following error:
`Unable to start cfn-lint (Error: spawn cfn-lint ENOENT). Is cfn-lint installed correctly?`

Any help would be appreciated.
Thanks!

Kind Regards,
Tomislav

**Comment by kddejong** [comment]
By default it will look for cfn-lint in the PATHs available to VSCode.  When installing it into user space you will need to make sure VSCode has that path available or manually specify the full path with a setting that is made available.

By default it will be this:
```
"cfnLint.path": "cfn-lint"
```
An example of hardcoding the path:
```
"cfnLint.path": "/Users/userid/Library/Python/3.6/bin/cfn-lint"
```

**Comment by kddejong** [comment]
@skokovic did that work?

**Comment by waynefk** [comment]
Using this on Windows and getting the same error. The path where cfn-lint installed is actually "cfnlint". I hardcoded the path and it still didn't like it.

**Comment by kddejong** [comment]
what version of `cfn-lint` are you using?  There was some changes that SAM put in that are better handled in the newest version of `cfn-lint` but I want to validate.

**Comment by anshul07** [comment]
For the SAM templates, I get the following error in VScode - 

[cfn-lint] E0001:Error transforming template: module 'samtranslator.parser.parser' has no attribute 'logging'

**Comment by EslamElHusseiny** [comment]
Hi,
I have the error `[cfn-lint] Unable to start cfn-lint (Error: spawn /bin/sh ENOENT). Is cfn-lint installed correctly?`

I've changed the `cfnLint.path` to be `"cfnLint.path": "/usr/local/bin/cfn-lint"` but I'm still getting the same error.
```
$ which cfn-lint 
/usr/local/bin/cfn-lint

$ cfn-lint --version 
cfn-lint 0.25.1

$ code --version 
1.40.1
8795a9889db74563ddd43eb0a897a2384129a619
x64
```

**Comment by mrpadigala** [comment]
Can someone help how to hardcode the path
"cfnLint.path": "/Users/userid/Library/Python/3.6/bin/cfn-lint"

**Comment by polarizeme** [comment]
> Can someone help how to hardcode the path
> "cfnLint.path": "/Users/userid/Library/Python/3.6/bin/cfn-lint"

In VSCode, go into the extensions sidebar, click the settings gear on the `CloudFormation Linter` extension, select extension settings, then define the path in the settings file or the applicable settings field in the GUI. Hope this helps!

**Comment by ysfk** [comment]
Better still just add the cfn-lint.exe directory to PATH variable in environment variables. (C:\Users\<userid>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\)

**Comment by PatMyron** [comment]
@ystoneman wonder if expanding `%USERPROFILE%` might help

**Comment by ystoneman** [comment]
> @ystoneman wonder if expanding `%USERPROFILE%` might help

thanks @PatMyron -- I did try that as well. By the way, I'm using Python 3.7 here.
