### ISSUE TITLE
This plugin bundles a vulnerable npm package!

### ISSUE THREAD

**Issue by JGjorgji** [awslabs/aws-cfn-lint-visual-studio-code#30]
https://github.com/dominictarr/event-stream/issues/116

More concretely `flatmap-stream`, is a vulnerable version `1.1.0`. Please update or pull this extension!

**Comment by kddejong** [comment]
thanks @JGjorgji  going to downgrade event-stream.  Looks like I have dependencies that aren't up dated yet.  This removes flatmap-stream completely.
