### ISSUE TITLE
Extension Marked As Malicious

### ISSUE THREAD

**Issue by sc-pulsion** [awslabs/aws-cfn-lint-visual-studio-code#32]
Hi you have probably been notified, but your extension seemingly included the event-stream npm package that had security issues.

https://code.visualstudio.com/blogs/2018/11/26/event-stream

**Comment by kddejong** [comment]
Yes it is updated.  0.4.0 is published that shouldn't include the bad version of event stream.  Back dated event-stream to 3.3.4  #31

**Comment by kddejong** [comment]
Unfortunately they still have it marked.  I'm trying to figure out how to get that removed.

**Comment by iloveicedgreentea** [comment]
VSMarketplace@microsoft.com from https://github.com/Microsoft/vscode/issues/33782

**Comment by cmmeyer** [comment]
Thanks @iloveicedgreentea  -- we'll reach out to that email address!

**Comment by benmontour-wf** [comment]
Thanks for the quick response to an unexpected issue!

**Comment by kddejong** [comment]
Took a little bit but the VsCode team got it rescanned and re-enabled last night.  We are available again.

**Comment by sc-pulsion** [comment]
Thanks for your quick help. Its a really helpful extension.

**Comment by kddejong** [comment]
Thank you @sc-pulsion.  And I apologize for any inconvenience.
