### ISSUE TITLE
Path to cfn-lint on Windows

### ISSUE THREAD

**Issue by jfeyers** [awslabs/aws-cfn-lint-visual-studio-code#33]
I'm getting the same error as mentioned here: [https://github.com/awslabs/aws-cfn-lint-visual-studio-code/issues/21#issue-366793312](https://github.com/awslabs/aws-cfn-lint-visual-studio-code/issues/21#issue-366793312), but I've tried changing the "Path to cfn-lint" setting to the path of my global install of cfn-lint (looks like C:\Users\\{username}\AppData\Roaming\npm\node_modules\cfn-lint). I can call cfn-lint from the command-line.

I'm sure it's just user error and an easy fix...any help would be appreciated.

**Comment by cmmeyer** [comment]
Heya --

Soooooo, fun fact: There are TWO cfn-lint binaries.  Based on the path, it looks like you have Marty Sweet's linter, which was written in node.  This VS Code extension is designed to be used with AWS Labs linter, which was written in the Python.  You'll want to do a pip install of the AWS Labs' linter and then point the extension to that (I'm not sure if Marty's linter has an equivalent VS Code extension).

**Comment by mariopoeta** [comment]
So i have installed CFN-linter through pip and i am using pycharm. Pycharm extension in windows ask me for exe or file to start it. Which file should i use? i tried main.py inside pip cnflinter folder and does not work

**Comment by PatMyron** [comment]
@karmendra shouldn't the end of the PATH be `cfn-lint` instead of `cfnlint`?
