### ISSUE TITLE
Include rule IDs in title/description

### ISSUE THREAD

**Issue by DrStrangepork** [awslabs/aws-cfn-lint-visual-studio-code#34]
I have CF templates that use embedded parameters, so my templates indicate several problems which are not problems. I have no idea what rule to include in the ignore list, because there is no translation to description to rule ID. For example, I have about 30 errors of "Found an embedded parameter...", but that string shows up nowhere in the cfn-lint code, so I have no idea how to avoid reporting on it.

**Comment by kddejong** [comment]
Rule E1029 I believe is what you are looking for.  If possible I would like to understand what resource and property you are having this issue with... or a small sample of the code. If your template is correct I would like to fix the errors so others and you don’t have to disable the rule.

**Comment by kddejong** [comment]
Also I will see what we can do about including the ID.  Thanks
