### ISSUE TITLE
Honor ignore rules in .cfnlintrc

### ISSUE THREAD

**Issue by cervantek** [awslabs/aws-cfn-lint-visual-studio-code#44]
I see the plugin setting "cfnLint.ignoreRules" as a way of ignoring rules, and it works. Would it be possible that the plugin instead could be configured to honor the .cfnlintrc, where those ignore-rules are already defined for the cfn-lint command line utility? This would make it so users do not have to maintain their list of ignore rules in two places.

This would also enable per-repo overrides, as that .cfnlintrc usually exists in the root directory of a repo. It appears that currently  "cfnLint.ignoreRules" is only configurable in user settings rather than folder settings in VS Code.

**Comment by cmmeyer** [comment]
Heya @cervantek -- I just tested it myself and confirmed the linter honors the .cfnlintrc in the root of the project.  For instance, here is the .cfnlintrc I put in the root of my AWSCloudFormationTemplates/ directory:

```
templates:
- '*.yml'
regions:
- us-west-2
ignore_checks:
- W3005
- W2509
```

Note that it needs to be in the root of the *project*, not just the repo.  Does that not work for you?

**Comment by cervantek** [comment]
I was trying to figure this out again by moving some files around, and discovered that once I removed the cfnLint.ignoreRules from my user-level settings.json, then the plugin began honoring the list of ignore_checks in the repo/folder-level .cfnlintrc. I really want the .cfnlintrc ones honored, and do not care as much about having user-level ignores, so my needs are met.

Just checking though... is this the intended behavior (for .cfnlintrc to be ignored if settings are defined in settings.json)? If so, please close the issue.

Alternatively, if the plugin merge the list from settings.json and the .cfnlintrc, then perhaps keep this issue open to track that.

**Comment by kddejong** [comment]
Sorry for the delay in response here.  We don't merge these items right now.  This plugin uses settings to feed to the command line of `cfn-lint`.  Command line arguments take ultimate precedence so your cfnlintrc gets ignored.  

Interesting thought around merging those items together.  It may be a feature request for how cfn-lint handles this.

**Comment by kddejong** [comment]
Going to close as it is working as expected.

**Comment by vennemp** [comment]
@cmmeyer I am working on a yaml project that has no CloudFormation templates and want to exclude all yaml in the project.

```yaml
##ignore yaml files in this project from being consumed by VS Code's CFN-Lint plugin
ignore-templates:
- '*.yml'
- '*.yaml'
```

```yaml
##ignore yaml files in this project from being consumed by VS Code's CFN-Lint plugin
ignore-templates:
- '**/*.yml'
- '**/*.yaml'
```


I have added this to the .cfnlintrc and put it at the root of my repo, which is what i use as the root of my project.  It is still not omitting my yaml files from being scanned.  Any ideas?
