### ISSUE TITLE
Latest Update Is Broken

### ISSUE THREAD

**Issue by sgtoj** [awslabs/aws-cfn-lint-visual-studio-code#66]
Latest Update (10/31/2019, 9:01:32 AM) now show 10s, if not 100s, of linter errors.

```
Version: 1.40.0-insider (user setup)
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T05:42:33.138Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19008

**Comment by sgtoj** [comment]
I have update the `cfn-lint` pip package and schemas (`cfn-lint -u`).

**Comment by kddejong** [comment]
Looking at it.  I believe its related to the YAML Schema stuff.  `"yaml.validate": false` in your settings will, I believe, fix it.

Going to work on a way to set that so it isn't enabled by default.

**Comment by kddejong** [comment]
@sgtoj just published a patch can you install this new version and see if that helps.

**Comment by sgtoj** [comment]
The patch and/or setting did resolve the issues. I will close this issue. I may provide additional feedback through another github issue.

**Comment by kddejong** [comment]
That's fair.  Thanks for reporting the issue @sgtoj and let me know if you have any more concerns.

**Comment by sgtoj** [comment]
I never said thank you....

Thank you for your quick response and resolution.
