### ISSUE TITLE
Add Missing Custom YAML Tags

### ISSUE THREAD

**Issue by sgtoj** [awslabs/aws-cfn-lint-visual-studio-code#69]
The previous issue -- #66  -- was caused missing custom tags. The following value for `yaml.customTag` setting allows for `yaml.validate` to be `enable` for CloudFormation template. I will update this issue if I find others.

```
  "yaml.customTags": [
    "!fn",
    "!And",
    "!And sequence",
    "!If",
    "!If sequence",
    "!Not",
    "!Not sequence",
    "!Equals",
    "!Equals sequence",
    "!Or",
    "!Or sequence",
    "!FindInMap",
    "!FindInMap sequence",
    "!Base64",
    "!Join",
    "!Join sequence",
    "!Cidr",
    "!Ref",
    "!Sub",
    "!Sub sequence",
    "!GetAtt",
    "!GetAZs",
    "!ImportValue",
    "!ImportValue sequence",
    "!Select",
    "!Select sequence",
    "!Split",
    "!Split sequence"
  ],

**Comment by kddejong** [comment]
thanks @sgtoj .

**Comment by kddejong** [comment]
Updated this in v0.10.2 which will be out very shortly.

**Comment by kddejong** [comment]
@sgtoj I used your list instead of what is here https://github.com/redhat-developer/yaml-language-server/issues/77.  Your list seems complete and more valid.

**Comment by tracphil** [comment]
Unless I am missing anything, this has not been resolved unless I am missing something in my settings.

My settings.json relevant parts:

```json
    "cfnLint.validateUsingJsonSchema": false,
    "yaml.customTags": [
        "!And",
        "!And sequence",
        "!If",
        "!If sequence",
        "!Not",
        "!Not sequence",
        "!Equals",
        "!Equals sequence",
        "!Or",
        "!Or sequence",
        "!FindInMap",
        "!FindInMap sequence",
        "!Base64",
        "!Join",
        "!Join sequence",
        "!Cidr",
        "!Ref",
        "!Sub",
        "!Sub sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!ImportValue sequence",
        "!Select",
        "!Select sequence",
        "!Split",
        "!Split sequence"
    ],
    "yaml.format.enable": false,
    "yaml.validate": false
```

With those settings, I am still getting (lots of others, this is an example):

`unknown tag: <!Sub>`

I am not sure whether others are seeing this or if I should open a new issue, so I thought I would mention it here first.

**Comment by tracphil** [comment]
Updating for the fix that help me. I removed the Ansible extension and this extension started working as expected.
